### ISSUE TITLE
Pure-go producer application (basic)

### ISSUE THREAD

**Issue by cataliniordache** [cmscaltech/sandie-ndn#8]

**Comment by cataliniordache** [comment]
Waiting for producer support in NDN-Go API

**Comment by yoursunny** [comment]
Prefix announcement feature is in NDNgo since https://github.com/usnistgov/ndn-dpdk/commit/a6691ec5bfc07c454922f2a80c921029f589d073.

`ndndpdk-godemo pingserver` has an example. Pay attention to these parts:
https://github.com/usnistgov/ndn-dpdk/blob/1586ca4294ccb7e1d24844fce7bf6c1856009eb6/cmd/ndndpdk-godemo/main.go#L27-L38
https://github.com/usnistgov/ndn-dpdk/blob/1586ca4294ccb7e1d24844fce7bf6c1856009eb6/cmd/ndndpdk-godemo/ping.go#L46-L53
Hint: you can use a separate `endpoint.Produce()` for each name prefix, e.g. `/ndn/xrootd/fileinfo` and `/ndn/xrootd/read`.

Note that you cannot run multiple producers with the same name prefix while doing prefix registration with package gqlmgmt. See https://github.com/usnistgov/ndn-dpdk/issues/10 .

**Comment by cataliniordache** [comment]
Thank you @yoursunny for your efforts and for delivering this even earlier than promise. I will start working on it and let you know what are the results.
